<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_employeesleave</name>
   <tag></tag>
   <elementGuidId>bea463df-bfd2-4637-8d00-4d4a881bbc93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[4]/div/div[1]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[4]/div/div[1]/div/p</value>
      <webElementGuid>ceeb2302-8f81-4434-8cb8-3edaa00647fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
