<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_timeatwork</name>
   <tag></tag>
   <elementGuidId>3d6cc5c2-2449-4084-bb92-57d66db0bc08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[1]/div/div[1]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[1]/div/div[1]/div/p</value>
      <webElementGuid>bc580b3b-668e-4eb0-9d26-5f3e98f3592b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
