<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_myactions</name>
   <tag></tag>
   <elementGuidId>52ed940b-3158-4088-a30e-29b92a904644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[2]/div/div[1]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[2]/div/div[1]/div/p</value>
      <webElementGuid>baefd44f-118f-4d29-b788-ae1090c63eab</webElementGuid>
   </webElementProperties>
</WebElementEntity>
